version: '3.8'

services:
  rk-mcu-sim:
    image: rust:1-bookworm
    working_dir: /work
    restart: unless-stopped
    # builder-only; no device access needed
    environment:
      - RK_MCU_SLAVE_PATH_FILE=/opt/printer_data/run/mcu_slave_path
    command: >
      sh -c "set -e; rustc --version || true; cargo build -p rk-mcu --features simulator; tail -f /dev/null"
    volumes:
      - ../../:/work
    profiles:
      - mainsail

  klipper:
    tty: true
    volumes:
      - /dev:/dev
      - ../../:/work
    entrypoint: ["/bin/sh","/work/external/prind/klipper-entry.sh"]
    logging:
      driver: json-file
    depends_on:
      init:
        condition: service_started
      rk-mcu-sim:
        condition: service_started

  moonraker:
    depends_on:
      init:
        condition: service_started
      klipper:
        condition: service_started
