version: '3.8'

services:
  rk-mcu-sim:
    image: rust:1-bookworm
    working_dir: /work
    restart: unless-stopped
    privileged: true
    environment:
      - RK_MCU_SLAVE_PATH_FILE=/opt/printer_data/run/mcu_slave_path
    command: >
      sh -c "cargo run -p rk-mcu --features simulator &
      while [ ! -s /opt/printer_data/run/mcu_slave_path ]; do sleep 0.1; done;
      PTY=$(cat /opt/printer_data/run/mcu_slave_path);
      [ -n \"$PTY\" ] && chmod 666 \"$PTY\" || true;
      [ -n \"$PTY\" ] && ln -sf \"$PTY\" /opt/printer_data/run/klipper_host_mcu.tty || true;
      tail -f /dev/null"
    volumes:
      - ../../:/work
      - run:/opt/printer_data/run
      - /dev:/dev
    profiles:
      - mainsail

  klipper:
    user: root
    group_add:
      - tty
    pid: "service:rk-mcu-sim"
    depends_on:
      rk-mcu-sim:
        condition: service_started
